kind: pipeline
name: releasing 1.0 for tester

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm run build

- name: deploy
  image: lucap/drone-netlify
  settings:
    token: # ff1b452e2e2511c85b975dcb3d6b7c3f0c3644e24a63bb39b127c780a5361c75
      from_secret: netlify_token
    site_id: 19eb59fb-9324-4261-866e-f5dffe2ebfed
    site_name: staging
    path: ./dist
    environment: staging

trigger:
    branch:
    - release/1.0 # Can not use wildcard as "release/*"