kind: pipeline
name: releasing 1.0 for tester

steps:
  - name: build
    image: node
    commands:
      - npm i
      - npm run build

trigger:
    branch:
    # 无法使用“release/*”模式
    - release/1.0
