kind: pipeline
name: releasing 1.0 for tester

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: build
  image: node
  commands:
  - npm config set registry "https://registry.npm.taobao.org"
  - npm install lodash

#- name: build
#  image: node
#  commands:
#  - npm install
#  - npm run build

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

- name: deploy
  image: lucap/drone-netlify
  settings:
    # get this from official site in your Personal access tokens,
    # it looks like ff1b452e2e2511c85b975dcb3d6b7c3f0c3644e24a63bb39b127c780a5361c75
    # then save it into Drone secrets
    token:
      from_secret: netlify_token
    # get this from official site in your Site settings dashboard
    site_id: 19eb59fb-9324-4261-866e-f5dffe2ebfed
    # define your own Netlify subdomain
    # site_name: staging-todo-shinvey
    path: ./dist

volumes:
- name: cache
  host:
    path: /home/shinvey/docker/volume/cache

trigger:
    branch:
    - release/1.0 # Can not use wildcard as "release/*"